name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - name: fmt --check
        run: cargo fmt --check
      - name: check
        run: cargo check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
      - name: test
        run: cargo test
