name: ci

on: [push, pull_request]

jobs:
  ci:
    name: Test `cargo fmt/check/clippy/test` on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - run: |
          cargo fmt --check
          cargo check
          cargo test
          cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
